# Generated by Django 3.2.5 on 2021-07-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=models.ImageField(blank=True, default='../static/image/avatar.png', upload_to='profile/'),
        ),
    ]
